name: gnash-raymii
base: core18 
version: '0.8.11-2' 
summary: GNU Gnash is the GNU Flash movie player
icon: snap/gui/gnash.png
description: |
  GNU Gnash is the GNU Flash movie player - Flash is an animation 
  file format pioneered by Macromedia which continues to be 
  supported by their successor company, Adobe. Flash has been 
  extended to include audio and video content, and programs written 
  in ActionScript, an ECMAScript-compatible language. Gnash is 
  based on GameSWF, and supports most SWF v7 features and some 
  SWF v8 and v9.  SWF v10 is not supported by GNU Gnash.

grade: stable 
confinement: strict 

parts:  
  gnash-raymii:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x gnash-wrapper
      chmod +x gnash-snap.desktop
      snapcraftctl build
    stage:
      - usr/bin/gnash-wrapper
      - usr/share/applications/gnash-snap.desktop
    organize:
      gnash-wrapper: usr/bin/gnash-wrapper
      gnash-snap.desktop: usr/share/applications/gnash-snap.desktop
  gnash-raymii:
    plugin: nil
    override-build: |
      snapcraftctl build
    stage-packages: 
      - gnash
      - gnash-common
      - python-gtk-gnash
      - gnash-cygnal
      - gnash-tools
      - libgl1
      - libslang2
      - libglu1-mesa
      - freeglut3

apps:
  gnash-raymii:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/gnash
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy
  gnash:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/gnash
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy
  dump-gnash:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/dump-gnash
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy      
  cygnal:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/cygnal
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy   
  flvdumper:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/flvdumper
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy   
  rtmpget:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/rtmpget
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy   
  soldumper:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/soldumper
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy   
  gprocessor:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
      LANG: C.UTF-8
    command: usr/bin/gprocessor
    plugs:
      - home
      - network
      - audio-playback
      - x11
      - alsa
      - desktop
      - desktop-legacy   
