name: bzr-explorer 
base: core18 
version: '0.1' 
summary: Desktop application for using the Bazaar Version Control System 
description: |
  Bazaar Explorer is a desktop application for using the Bazaar Version Control 
  System. It provides a high level interface to all commonly used features, 
  launching "applets" from the QBzr plug-in to provide most of the functionality. 
  Alternatively, the applets from the bzr-gtk plug-in can be used if it is 
  installed. Bazaar Explorer runs on GNOME, KDE, Windows, Mac OS X and FreeBSD.

grade: stable 
confinement: classic 

parts:  
  bzr-explorer-wrapper:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x wrapper
      chmod +x bzr-explorer-snap.desktop
      snapcraftctl build
    stage:
      - usr/bin/wrapper
      - usr/share/applications/bzr-explorer-snap.desktop
      - usr/share/pixmaps/bzr-explorer-snap.png
    organize:
      wrapper: usr/bin/wrapper
      bzr-explorer-snap.desktop: usr/share/applications/bzr-explorer-snap.desktop
      bzr-explorer-snap.png: usr/share/pixmaps/bzr-explorer-snap.png
  bzr-explorer:
    plugin: nil
    override-build: |
      snapcraftctl build
      cp -v $SNAPCRAFT_PART_INSTALL/usr/bin/bzr.bzr $SNAPCRAFT_PART_INSTALL/usr/bin/bzr
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/bzr
    stage-packages: 
      - bzr
      - bzr-explorer

apps:
  bzr-explorer:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
    desktop: usr/share/applications/bzr-explorer-snap.desktop
    command: wrapper