name: gnash
base: core18 
version: '0.8.11' 
summary: GNU Gnash is the GNU Flash movie player
description: |
  
  GNU Gnash is the GNU Flash movie player — Flash is an animation 
  file format pioneered by Macromedia which continues to be 
  supported by their successor company, Adobe. Flash has been 
  extended to include audio and video content, and programs written 
  in ActionScript, an ECMAScript-compatible language. Gnash is 
  based on GameSWF, and supports most SWF v7 features and some 
  SWF v8 and v9.  SWF v10 is not supported by GNU Gnash.

grade: stable 
confinement: classic 

parts:  
  gnash-wrapper:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x wrapper
      chmod +x gnash-snap.desktop
      snapcraftctl build
    stage:
      - usr/bin/wrapper
      - usr/share/applications/gnash-snap.desktop
      - usr/share/pixmaps/gnash-snap.png
    organize:
      wrapper: usr/bin/wrapper
      gnash-snap.desktop: usr/share/applications/gnash-snap.desktop
      gnash-snap.png: usr/share/pixmaps/gnash-snap.png
  gnash:
    plugin: nil
    override-build: |
      snapcraftctl build
    stage-packages: 
      - gnash

apps:
  gnash:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7/site-packages:$SNAP/usr/lib/python2.7/dist-packages:$PYTHONPATH
    desktop: usr/share/applications/gnash-snap.desktop
    command: wrapper
